const TRACE_SUPABASE_URL="https://yyxoswvvoterhnytxsdt.supabase.co";
const TRACE_SUPABASE_KEY="sb_publishable_xoRToZ5fS-clYqbNy3ucXA__d_pVFKe";
let traceSupabase=null,traceUser=null,traceSaveTimer=null,traceCloudReady=false;
async function traceInitCloud(){try{if(!window.supabase||!window.supabase.createClient){console.warn("TRACE cloud save unavailable: Supabase client library missing");return false}traceSupabase=window.supabase.createClient(TRACE_SUPABASE_URL,TRACE_SUPABASE_KEY);let s=await traceSupabase.auth.getSession();traceUser=s.data.session?.user||null;if(!traceUser){let r=await traceSupabase.auth.signInAnonymously();if(r.error)throw new Error("Anonymous sign-in failed: "+r.error.message);traceUser=r.data.user||null}if(traceUser){traceCloudReady=true;await traceLoadCloud();await traceSaveNow();return true}return false}catch(e){console.warn("TRACE cloud save unavailable",e);return false}}
function tracePayload(){return {version:1,playerName:state.playerName,phase:Number(document.body.dataset.tracePhase||0),anomalyStep,storyFlags,files:state.files,notes:state.notes,calculatorGlitch:state.calculatorGlitch,clockGlitch:state.clockGlitch,alerts:state.alerts,settings:{dark:state.dark,notifications:state.notifications,sound:state.sound,volume:state.volume},tetrisHighScore:Number(localStorage.getItem("trace_tetris_high")||0),transferAccessed:localStorage.getItem("trace_transfer_accessed")==="1",previousSessionSeen:localStorage.getItem("trace_previous_session_seen")==="1",previousSessionStep:Number(localStorage.getItem("trace_maya_previous_session_step")||0),previousSessionComplete:localStorage.getItem("trace_maya_previous_session_complete")==="1",maya:{step:Number(localStorage.getItem("trace_maya_step")||0),choices:JSON.parse(localStorage.getItem("trace_maya_choices")||"[]")},savedAt:new Date().toISOString()}}
async function traceSaveNow(){try{let payload=tracePayload();localStorage.setItem("trace_save",JSON.stringify(payload));if(!traceCloudReady||!traceSupabase||!traceUser)return;let r=await traceSupabase.from("trace_saves").upsert({user_id:traceUser.id,player_name:state.playerName,phase:payload.phase,save_data:payload,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(r.error)throw new Error("Cloud save failed: "+r.error.message);console.log("TRACE cloud save complete",traceUser.id)}catch(e){console.warn("TRACE save failed",e)}}
function traceQueueSave(){clearTimeout(traceSaveTimer);traceSaveTimer=setTimeout(traceSaveNow,350)}
function traceApplyPayload(p){if(!p)return false;state.playerName=p.playerName||state.playerName;state.files=Array.isArray(p.files)?p.files:state.files;state.notes=p.notes||state.notes;state.calculatorGlitch=!!p.calculatorGlitch;state.clockGlitch=!!p.clockGlitch;if(p.settings){state.dark=p.settings.dark!==false;state.notifications=p.settings.notifications!==false;state.sound=p.settings.sound!==false;state.volume=Number(p.settings.volume??state.volume)}if(p.anomalyStep!=null)anomalyStep=Number(p.anomalyStep)||0;if(p.storyFlags)storyFlags=p.storyFlags;if(p.phase!=null)document.body.dataset.tracePhase=String(p.phase);if(p.tetrisHighScore!=null)localStorage.setItem("trace_tetris_high",String(Number(p.tetrisHighScore)||0));if(p.transferAccessed)localStorage.setItem("trace_transfer_accessed","1");if(p.previousSessionSeen)localStorage.setItem("trace_previous_session_seen","1");if(p.previousSessionStep!=null)localStorage.setItem("trace_maya_previous_session_step",String(Number(p.previousSessionStep)||0));if(p.previousSessionComplete)localStorage.setItem("trace_maya_previous_session_complete","1");if(p.maya){localStorage.setItem("trace_maya_step",String(p.maya.step||0));localStorage.setItem("trace_maya_choices",JSON.stringify(p.maya.choices||[]))}localStorage.setItem("trace_player_name",state.playerName||"");return true}
async function traceLoadCloud(){try{let r=await traceSupabase.from("trace_saves").select("player_name,phase,save_data").eq("user_id",traceUser.id).maybeSingle();if(r.error)throw new Error(r.error.message);if(r.data?.save_data){traceApplyPayload(r.data.save_data);localStorage.setItem("trace_save",JSON.stringify(r.data.save_data));return true}let local=JSON.parse(localStorage.getItem("trace_save")||"null");if(local){traceApplyPayload(local);await traceSaveNow();return true}return false}catch(e){console.warn("TRACE cloud load failed",e);let local=JSON.parse(localStorage.getItem("trace_save")||"null");if(local)traceApplyPayload(local);return !!local}}
window.addEventListener("pagehide",traceSaveNow);
